version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# Build additional formats for convenient downloads
formats:
  - htmlzip
  - pdf

python:
  install:
    - requirements: docs/requirements.txt

# If you prefer a conda env instead of requirements.txt, uncomment below and
# add a docs/environment.yml file. RTD uses mambaforge for speed.
#conda:
#  environment: docs/environment.yml
